-- Migration: Add ai_generated column and tip_categories table
-- This migration enables fully dynamic AI-powered tip generation
-- Note: preschool stage already exists in the database CHECK constraint

-- =====================================================
-- 1. Add ai_generated column to daily_tips table
-- =====================================================

ALTER TABLE daily_tips 
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE;

COMMENT ON COLUMN daily_tips.ai_generated IS 'Whether this tip was generated by AI (DeepSeek) or from static templates';

-- Add unique constraint for user_id + tip_date to prevent duplicates
-- (Allows upsert in Edge Function)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'daily_tips_user_date_unique'
  ) THEN
    ALTER TABLE daily_tips 
    ADD CONSTRAINT daily_tips_user_date_unique UNIQUE (user_id, tip_date);
  END IF;
END$$;

-- =====================================================
-- 2. Create tip_categories table for dynamic category management
-- =====================================================

CREATE TABLE IF NOT EXISTS tip_categories (
  id UUID PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  name TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  description TEXT,
  icon TEXT DEFAULT 'Lightbulb',
  color TEXT DEFAULT '#E07A5F',
  parenting_stages TEXT[] DEFAULT ARRAY['expecting', 'newborn', 'infant', 'toddler', 'preschool'],
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE tip_categories ENABLE ROW LEVEL SECURITY;

-- Everyone can read categories (public data)
CREATE POLICY "Anyone can view tip categories"
  ON tip_categories FOR SELECT
  USING (true);

-- Create index for active categories
CREATE INDEX IF NOT EXISTS idx_tip_categories_active 
  ON tip_categories(is_active, sort_order);

-- Add comments
COMMENT ON TABLE tip_categories IS 'Dynamic tip categories with display metadata and stage restrictions';
COMMENT ON COLUMN tip_categories.name IS 'Machine-readable category name (e.g., sleep, feeding)';
COMMENT ON COLUMN tip_categories.display_name IS 'Human-readable name for UI display';
COMMENT ON COLUMN tip_categories.icon IS 'Icon name from the app icon library';
COMMENT ON COLUMN tip_categories.color IS 'Hex color code for category theming';
COMMENT ON COLUMN tip_categories.parenting_stages IS 'Which parenting stages this category applies to';

-- =====================================================
-- 3. Seed default tip categories
-- =====================================================

INSERT INTO tip_categories (name, display_name, description, icon, color, parenting_stages, sort_order)
VALUES
  ('sleep', 'Sleep & Rest', 'Tips for healthy sleep routines and schedules', 'Moon', '#6366F1', 
   ARRAY['newborn', 'infant', 'toddler', 'preschool'], 1),
  
  ('feeding', 'Feeding & Nutrition', 'Breastfeeding, formula, solids, and healthy eating', 'Utensils', '#F59E0B',
   ARRAY['expecting', 'newborn', 'infant', 'toddler', 'preschool'], 2),
  
  ('development', 'Growth & Development', 'Milestones, learning, and cognitive development', 'TrendingUp', '#10B981',
   ARRAY['expecting', 'newborn', 'infant', 'toddler', 'preschool'], 3),
  
  ('health', 'Health & Wellness', 'Illness prevention, checkups, and common concerns', 'Heart', '#EF4444',
   ARRAY['expecting', 'newborn', 'infant', 'toddler', 'preschool'], 4),
  
  ('behavior', 'Behavior & Discipline', 'Understanding behavior and gentle guidance', 'Brain', '#8B5CF6',
   ARRAY['infant', 'toddler', 'preschool'], 5),
  
  ('activities', 'Play & Activities', 'Age-appropriate games, toys, and learning activities', 'Puzzle', '#EC4899',
   ARRAY['newborn', 'infant', 'toddler', 'preschool'], 6),
  
  ('safety', 'Safety & Childproofing', 'Home safety, car seats, and injury prevention', 'Shield', '#14B8A6',
   ARRAY['expecting', 'newborn', 'infant', 'toddler', 'preschool'], 7),
  
  ('bonding', 'Bonding & Connection', 'Building attachment and emotional connection', 'Heart', '#E07A5F',
   ARRAY['expecting', 'newborn', 'infant', 'toddler', 'preschool'], 8)
ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  parenting_stages = EXCLUDED.parenting_stages,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();

-- =====================================================
-- 4. Add indexes for better query performance on daily_tips
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_daily_tips_user_date 
  ON daily_tips(user_id, tip_date DESC);

CREATE INDEX IF NOT EXISTS idx_daily_tips_category 
  ON daily_tips(category);

CREATE INDEX IF NOT EXISTS idx_daily_tips_ai_generated 
  ON daily_tips(ai_generated);

